backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "content/assets/images"
public_folder: "/assets/images"

collections:
  - label: "Project"
    name: "project"
    folder: "content/project"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Preview link", name: "preview_link", widget: "string", required: false, default: null }
      - { label: "Code link", name: "code_link", widget: "string", required: false, default: null }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
  - label: "Skill"
    name: "skill"
    folder: "content/skill"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Rating", name: "rating", widget: "number", value_type: "int", min: 0, max: 100 }
